# Generated by Django 3.2.12 on 2022-04-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='filestored',
        ),
    ]
