# Generated by Django 3.2.12 on 2022-04-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_file_file_filestored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filestored',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='index',
            new_name='filepath',
        ),
    ]
