# Generated by Django 3.2.12 on 2022-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220407_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filepath',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.AddField(
            model_name='file',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
