# Generated by Django 3.2.12 on 2022-04-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220414_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
