# Generated by Django 3.2.12 on 2022-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='imagefile',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
