# Generated by Django 3.2.12 on 2022-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_fileupload_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='imagefile',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
