# Generated by Django 3.2.12 on 2022-05-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_fileupload_imagefile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='ImageStorage',
        ),
    ]
