# Generated by Django 3.2.12 on 2022-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_fileupload_imagestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
